### ISSUE TITLE
项目构建问题

### ISSUE THREAD

**Issue by BLC-SGTQ** [pcyanga/young#1]
你好，我想用young作为我毕设的后端，现在构建完项目后有些问题想请教一下。
1.npm run dev 后出现如图报错
![p1](https://user-images.githubusercontent.com/58133228/141990275-b4e37233-bca8-4a0c-b80a-8611c63290d4.png)
这是否是中文路径的问题？还是说 需要修改node_modules\young-core\lib\typings.js中第7行的fileBase路径？

2.使用npm run start 运行项目后，项目在pm2中运行成功但是typeORM未在数据库中生成表 配置如图
![p4](https://user-images.githubusercontent.com/58133228/141991941-824336ee-b7f7-42c0-812a-cfa3ba995e5e.jpg)
![p3](https://user-images.githubusercontent.com/58133228/141991301-a0a3b6fc-de07-44b4-b95a-5d25d96257c1.png)
![p2](https://user-images.githubusercontent.com/58133228/141991308-ede198c7-f3e2-4d49-8b62-8f88ca1e9039.png)

3.登录api中的file文件是做什么的，我阅读module\admin\user.ts 中的代码未用到这个文件。

我现在对项目有些懵懵懂懂，希望大佬能抽出时间解惑，感激不尽。

**Comment by pcyanga** [comment]
你可以看下logs下面的日志哈

**Comment by pcyanga** [comment]
1、需要贴下完整报错
2、start是正式环境，如果需要生成表，需要打开prod的synchronize:true
3、admin和api是前后台代码分离用的，这边只是作为示例，没有实际作用

**Comment by pcyanga** [comment]
有需要的话可以加在微信号：krally，互相交流学习
